ordinal_dict = {
    "BsmtCond": ['None', 'Po', 'Fa', 'TA', 'Gd'],
    "BsmtExposure": ['None', 'No', 'Mn', 'Av', 'Gd'],
    "BsmtFinType1": ['None', 'Unf', 'LwQ', 'Rec', 'BLQ', 'ALQ', 'GLQ'],
    "BsmtFinType2": ['None', 'Unf', 'LwQ', 'Rec', 'BLQ', 'ALQ', 'GLQ'],
    "BsmtQual": ['None', 'Fa', 'TA', 'Gd', 'Ex'],
    "Electrical": ['None', 'Mix', 'FuseP', 'FuseF', 'FuseA', 'SBrkr'],
    "ExterCond": ['None', 'Po', 'Fa', 'TA', 'Gd', 'Ex'],
    "ExterQual": ['None', 'Fa', 'TA', 'Gd', 'Ex'],
    "Fence": ['None', 'MnWw', 'GdWo', 'MnPrv', 'GdPrv'],
    "FireplaceQu": ['None', 'Po', 'Fa', 'TA', 'Gd', 'Ex'],
    "Functional": ['None', 'Sev', 'Maj2', 'Maj1', 'Mod', 'Min2', 'Min1', 'Typ'],
    "GarageCond": ['None', 'Po', 'Fa', 'TA', 'Gd', 'Ex'],
    "GarageFinish": ['None', 'Unf', 'RFn', 'Fin'],
    "GarageQual": ['None', 'Po', 'Fa', 'TA', 'Gd', 'Ex'],
    "HeatingQC": ['None', 'Po', 'Fa', 'TA', 'Gd', 'Ex'],
    "KitchenQual": ['None', 'Fa', 'TA', 'Gd', 'Ex'],
    "LandContour": ['None', 'Low', 'Bnk', 'HLS', 'Lvl'],
    "LandSlope": ['None', 'Sev', 'Mod', 'Gtl'],
    "LotShape": ['None', 'IR3', 'IR2', 'IR1', 'Reg'],
    "PavedDrive": ['None', 'N', 'P', 'Y'],
    "PoolQC": ['None', 'Fa', 'Gd', 'Ex'],
}
